<?php

namespace ContainerBE7jN6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHautelookAlice_Resolver_FileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hautelook_alice.resolver.file' shared service.
     *
     * @return \Hautelook\AliceBundle\Resolver\File\KernelFileResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/theofidry/alice-data-fixtures/src/FileResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/hautelook/alice-bundle/src/Resolver/File/KernelFileResolver.php';

        return $container->services['hautelook_alice.resolver.file'] = new \Hautelook\AliceBundle\Resolver\File\KernelFileResolver(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
