<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23index%5D%5B1%5D' => 3,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23index%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23saves%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23saves%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23gets%5D%5B1%5D' => 5,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23gets%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiAuthors%5D%5B1%5D' => 6,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiAuthors%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiAuthorsEdit%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiAuthorsEdit%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiAuthorsAll%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiAuthorsAll%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiAuthor%5D%5B1%5D' => 9,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiAuthor%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiBooks%5D%5B1%5D' => 10,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiBooks%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiBooksEdit%5D%5B1%5D' => 11,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiBooksEdit%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiBooksAll%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiBooksAll%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiBook%5D%5B1%5D' => 13,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiBook%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiBookDelete%5D%5B1%5D' => 14,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiBookDelete%5D%5B1%5D' => 2,
'%5BApp%5CController%5CAuthorBookController%23apiAuthorDelete%5D%5B1%5D' => 15,
'%5B%5BC%5DApp%5CController%5CAuthorBookController%23apiAuthorDelete%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%5D%5B1%5D' => 16,
'%5B%5BC%5DApp%5CEntity%5CAuthor%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23getName%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23getName%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23setName%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23setName%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23getEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23getEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23setEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23setEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23getBooksCount%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23getBooksCount%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%23setBooksCount%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthor%23setBooksCount%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%24id%5D%5B1%5D' => 17,
'%5B%5BC%5DApp%5CEntity%5CAuthor%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%24name%5D%5B1%5D' => 18,
'%5B%5BC%5DApp%5CEntity%5CAuthor%24name%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%24email%5D%5B1%5D' => 19,
'%5B%5BC%5DApp%5CEntity%5CAuthor%24email%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthor%24booksCount%5D%5B1%5D' => 20,
'%5B%5BC%5DApp%5CEntity%5CAuthor%24booksCount%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%5D%5B1%5D' => 21,
'%5B%5BC%5DApp%5CEntity%5CAuthors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthors%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%23getName%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthors%23getName%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%23getEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthors%23getEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%23setName%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthors%23setName%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%23setEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAuthors%23setEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%24id%5D%5B1%5D' => 22,
'%5B%5BC%5DApp%5CEntity%5CAuthors%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%24name%5D%5B1%5D' => 23,
'%5B%5BC%5DApp%5CEntity%5CAuthors%24name%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAuthors%24email%5D%5B1%5D' => 24,
'%5B%5BC%5DApp%5CEntity%5CAuthors%24email%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%5D%5B1%5D' => 25,
'%5B%5BC%5DApp%5CEntity%5CBook%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBook%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%23getTitle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBook%23getTitle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%23setTitle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBook%23setTitle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%23getAuthors%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBook%23getAuthors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%23setAuthors%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBook%23setAuthors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%24id%5D%5B1%5D' => 26,
'%5B%5BC%5DApp%5CEntity%5CBook%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%24title%5D%5B1%5D' => 27,
'%5B%5BC%5DApp%5CEntity%5CBook%24title%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBook%24authors%5D%5B1%5D' => 28,
'%5B%5BC%5DApp%5CEntity%5CBook%24authors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%5D%5B1%5D' => 29,
'%5B%5BC%5DApp%5CEntity%5CBooks%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBooks%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%23getTitle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBooks%23getTitle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%23getAuthors%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBooks%23getAuthors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%23setTitle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBooks%23setTitle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%23setAuthors%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CBooks%23setAuthors%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%24id%5D%5B1%5D' => 22,
'%5B%5BC%5DApp%5CEntity%5CBooks%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%24title%5D%5B1%5D' => 30,
'%5B%5BC%5DApp%5CEntity%5CBooks%24title%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CBooks%24authors%5D%5B1%5D' => 31,
'%5B%5BC%5DApp%5CEntity%5CBooks%24authors%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23__construct%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23decodePropertyPaths%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23decodePropertyPaths%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23encodePropertyPaths%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23encodePropertyPaths%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23decodePath%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23decodePath%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23encodePath%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23encodePath%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23getFilename%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23getFilename%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23getPropertyPaths%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23getPropertyPaths%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23withPropertyPaths%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23withPropertyPaths%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23getPropertyPathAsString%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23getPropertyPathAsString%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23__toString%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23__toString%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23setFromDefault%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23setFromDefault%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%23fromDefault%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%23fromDefault%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%24filename%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%24filename%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%24propertyPaths%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%24propertyPaths%5D%5B1%5D' => 2,
'%5BJsonSchema%5CEntity%5CJsonPointer%24fromDefault%5D%5B1%5D' => 1,
'%5B%5BC%5DJsonSchema%5CEntity%5CJsonPointer%24fromDefault%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 2,

], [

0 => 'N;',
1 => [],
2 => 1606435892,
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/author/book',
                ],
                'name' => [
                    'author_book',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/save',
                ],
                'name' => [
                    'save',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/gets',
                ],
                'name' => [
                    'gets',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/authors',
                ],
                'name' => [
                    'postAuthors',
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/authors/{id}',
                ],
                'name' => [
                    'putAuthors',
                ],
                'methods' => [
                    [
                        'PUT',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/authors',
                ],
                'name' => [
                    'getAllAuthors',
                ],
                'methods' => [
                    [
                        'GET',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/authors/{id}',
                ],
                'name' => [
                    '=getAuthor',
                ],
                'methods' => [
                    [
                        'GET',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/books',
                ],
                'name' => [
                    'postBooks',
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/books/{id}',
                ],
                'name' => [
                    'putBook',
                ],
                'methods' => [
                    [
                        'PUT',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/books',
                ],
                'name' => [
                    'getAllBooks',
                ],
                'methods' => [
                    [
                        'GET',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/books/{id}',
                ],
                'name' => [
                    '=getBook',
                ],
                'methods' => [
                    [
                        'GET',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/books/{id}/delete',
                ],
                'name' => [
                    '=delBook',
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/authors/{id}/delete',
                ],
                'name' => [
                    '=delAuthor',
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    1 => 'App\\Repository\\AuthorRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
17 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
18 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    500,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
19 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    200,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
20 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'integer',
                ],
                'options' => [
                    [
                        'default' => 0,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
21 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'authors',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
22 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'id',
                ],
                'type' => [
                    'integer',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
23 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'name',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
24 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'email',
                ],
                'length' => [
                    100,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
25 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    1 => 'App\\Repository\\BookRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
26 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    2 => '`id`',
                ],
                'type' => [
                    2 => 'integer',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
27 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    '`title`',
                ],
                'length' => [
                    500,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
28 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    '`authors`',
                ],
                'type' => [
                    'array',
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
29 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'books',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
30 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'title',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
31 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'authors',
                ],
                'type' => [
                    'array',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},

]];
