<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBE7jN6D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBE7jN6D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBE7jN6D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBE7jN6D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBE7jN6D\App_KernelDevDebugContainer([
    'container.build_hash' => 'BE7jN6D',
    'container.build_id' => '918a066e',
    'container.build_time' => 1606437902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBE7jN6D');
